#!/bin/sh

set -e
umask 0002

OPTIONS="--lock /etc/device/service/radius/ \
         --show - \
         --polar disabled"

if [ "$1" == "--" ]; then

  /usr/libexec/device-tool ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-tool ${OPTIONS} "$@"

fi

